class RubyForProgrammers < Course
  lesson "credits"
  lesson "meta"
  lesson "intro"
  lesson "basics/tools"
  lesson "basics/rspec"
  lesson "basics/more_neat_things"
  lesson "basics/functions"
  # lab "Hello"
  lesson "basics/types"
  lesson "basics/numbers"
  # lab "Temperature"
  # lab "Calculator"
  lesson "basics/conditionals"
  lesson "basics/strings"
  lesson "basics/chaining"
  # lab "Simon Says"
  lesson "basics/regexp"
  #lesson "# Ablay: Igpay Atinlay"
  lesson "basics/symbols"
  lesson "basics/loops"
  lesson "basics/collections"
  lesson "basics/arrays"
  # todo: lab on arrays
  lesson "basics/ranges"
  lesson "basics/hashes"
  # todo: lab on hashes
  lesson "basics/blocks"
  # lab "Blocks"
  lesson "basics/block_scope"
  lesson "basics/stubbing"
  # lab "Performance Monitor"
  lesson "basics/iterators"
  lesson "objects/waka-waka"

  lesson "objects/tiers"
  lesson "objects/objects"
  lesson "objects/classes"
  #lab "Hello Friend"
  #lesson /* todo: creation patterns */
  lesson "objects/class_inheritance"
  #lesson "# Lab:\n* Temperature Object\n* Book Titles\n* Timer\n* Dictionary\n"
  #lesson "# Lab:\n* RPN Calculator"
  lesson "objects/dispatch"
  #lesson "# Lab:\n* XML Builder"
  lesson "objects/class_methods"
  lesson "objects/reopening_classes"
  #lesson "# Labs:\n* Array Extensions\n* In Words\n"
  lesson "objects/modules"
  lesson "objects/variable_scope"
  lesson "objects/method_scope"

  lesson "basics/exceptions"
  #lesson /* todo: exception exercise */
  lesson "advanced/more_blocks"
  lesson "basics/enumerators_advanced"
  lesson "objects/classes_as_objects"
  lesson "basics/time"
  lesson "basics/io"
  #lesson /* todo: file/io exercise, like scraper */
  lesson "bad_names"

end
