require "course"

Course::LearnToCode = Course.new(name: "learn_to_code", display_name: "Learn to Code with Ruby") do
    lesson "intro"
    lesson "computers"
    lesson "ruby"
    lesson "objects"
    lesson "strings"
    lesson "numbers"
    lesson "variables"
    lesson "nil"
    lesson "the_command_line"
    lesson "input_and_output"
    lesson "logic"
    lesson "loops"
    lesson "arrays"
    lesson "argv"
    lesson "hashes"
    lesson "functions"
    lesson "sinatra"
    lesson "extra"
    lesson "next_steps"
    # lesson "methods"
    # lesson "classes"
end
